# Generated by Django 2.1.7 on 2019-06-04 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190424_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'PostS'},
        ),
    ]
