# Generated by Django 2.1.7 on 2019-06-06 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190606_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_bio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post_bio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
