# Generated by Django 2.1.7 on 2019-06-07 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190606_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('intro', models.TextField()),
                ('domain', models.TextField()),
                ('body', models.TextField()),
                ('image1', models.ImageField(upload_to='')),
                ('legende1', models.CharField(max_length=100)),
                ('image2', models.ImageField(upload_to='')),
                ('legende2', models.CharField(max_length=100)),
                ('image3', models.ImageField(upload_to='')),
                ('legende3', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='post_bio',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
