# Generated by Django 2.1.7 on 2019-06-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190607_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_projet',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
