# Generated by Django 2.1.7 on 2019-06-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190607_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_projet',
            name='domain',
            field=models.CharField(max_length=500),
        ),
    ]
