# Generated by Django 2.1.7 on 2019-06-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190607_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_projet',
            name='image1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post_projet',
            name='image2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post_projet',
            name='image3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post_projet',
            name='legende1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post_projet',
            name='legende2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post_projet',
            name='legende3',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
