# Generated by Django 2.1.7 on 2019-06-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190607_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_projet',
            name='image1',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='post_projet',
            name='image2',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='post_projet',
            name='image3',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
